config/routes.rb
Rails.application.routes.draw do
  namespace :staff,path: "" do
    root'top#index'
    get "login",to:"sessions#new", as: :login
    post "session",to:"sessions#create", as: :session
    delete "session",to:"sessions#destroy"
    resource :account
    resources :profile
  end
  namespace :admin do
    root'top#index'
    get "login",to:"sessions#new", as: :login
    post "session",to:"sessions#create", as: :session
    delete "session",to:"sessions#destroy"
    resources :staff_members
    resources :profile
  end
  namespace :customer do
    root'top#index'
    get "login",to:"sessions#new", as: :login
    post "session",to:"sessions#create", as: :session
    delete "session",to:"sessions#destroy"

  end
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    else
      self.hashed_password = nil if raw_password.nil?
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/staff_member.rb
class StaffMember < ApplicationRecord
  def password=(raw_password)
    if raw_password.kind_of?(String)
      self.hashed_password = BCrypt::Password.create(raw_password)
    else
      self.hashed_password = nil if raw_password.nil?
    end
  end
end

app/controllers/admin/base.rb
class Admin::Base < ApplicationController

  private def current_administrator
    if session[:administrator_id]
      @current_administrator ||=
          Administrator.find_by(id: session[:administrator_id])
    end
  end

  helper_method :current_administrator
end

app/controllers/admin/profile_controller.rb
class Admin::ProfileController < Admin::Base
  def index
    @staff_members = StaffMember.order(:family_name_kana,:given_name_kana)
  end
end

app/controllers/admin/sessions_controller.rb
class Admin::SessionsController < Admin::Base
  def new
    if current_administrator
      redirect_to :admin_root
    else
      @form = Admin::LoginForm.new
      render action: :new
    end
  end

  def create
    @form = Admin::LoginForm.new(login_form_params)
    if @form.email.present?
      administrator =
          Administrator.find_by("LOWER(email) = ?", @form.email.downcase)
    end
    if Admin::Authenticator.new(administrator).authenticate(@form.password)
      if administrator.suspended?
        flash.now.alert = "アカウントが停止されています。"
        render action: "new"
      else
        session[:administrator_id] = administrator.id
        flash.notice = "ログインしました。"
        redirect_to :admin_root
      end
    else
      flash.now.alert = "メールアドレスまたはパスワードが正しくありません。"
      render action: :new
    end
  end

  private def login_form_params
    params.require(:admin_login_form).permit(:email, :password)
  end

  def destroy
    session.delete(:administrator_id)
    flash.notice = "ログアウトしました。"
    redirect_to :admin_root
  end
end

app/controllers/admin/staff_members_controller.rb
class Admin::StaffMembersController < Admin::Base
  def index
    @staff_members = StaffMember.order(:family_name_kana,:given_name_kana)
  end
  def show
    staff_member = StaffMember.find(params[:id])
    redirect_to [:edit, :admin,staff_member]
  end
  def new
    @staff_member = StaffMember.new
  end
  def create
    @staff_member = StaffMember.new(staff_member_params)
    if @staff_member.save
      flash.notice = "職員アカントを新規登録しました"
      redirect_to :admin_staff_members
    else
      render :new
    end
  end
  def edit
    @staff_member = StaffMember.find(params[:id])
  end
  def update
    @staff_member = StaffMember.find(params[:id])
    @staff_member.assign_attributes(staff_member_params)
    if @staff_member.save
      flash.notice ="職員情報を更新しました"
      redirect_to :admin_staff_members
    else
      render :edit
    end
  end
  def destroy
    staff_member = StaffMember.find(params[:id])
    staff_member.destroy!
    flash.notice = "職員アカウントを削除しました"
    redirect_to :admin_staff_members
  end
  private
  def staff_member_params
    params.require(:staff_member).permit(:family_name,:given_name,:family_name_kana,:given_name_kana,:email,
                                         :hashed_password,:start_date,:end_date,:suspended,:created_at,:updated_at)
  end
end

app/controllers/admin/top_controller.rb
class Admin::TopController < Admin::Base
  def index
    if current_administrator
      render :dashboard
    else
      render :index
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :set_layout
  class Forbidden < ActionController::ActionControllerError;end
  class IpAddressRejected < ActionController::ActionControllerError;end


  private
  def set_layout
    if params[:controller].match(%r{\A(staff|admin|customer)/})
      Regexp.last_match[1]
    else
      "customer"
    end
  end
end

app/controllers/concerns/error_handlers.rb
module ErrorHandlers
  extend ActiveSupport::Concern
  included do
    rescue_from StandardError, with: :rescue500
    rescue_from Forbidden, with: :rescue403
    rescue_from IpAddressRejected, with: :rescue403
  end
  private
  def rescue500(e)
    render "errors/internal_server_error",status: 500
  end
  def rescue403(e)
    @exception = e
    render "errors/forbidden",status: 403
  end
end

app/controllers/customer/sessions_controller.rb
class Customer::SessionsController < ApplicationController
end

app/controllers/customer/top_controller.rb
class Customer::TopController < ApplicationController
  def index; end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  layout "staff"

  def not_found
    render status: 404
  end
  def unprocessable_entity
    render status: 422
  end
  def internal_server_error
    render status: 500
  end
end

app/controllers/staff/base.rb
class Staff::Base < ApplicationController
  private def current_staff_member
    if session[:staff_member_id]
      @current_staff_member ||=
          StaffMember.find_by(id: session[:staff_member_id])
    end
  end

  helper_method :current_staff_member
  def staff_member_params
    params.require(:staff_member).permit(:family_name,:given_name,:family_name_kana,:given_name_kana,
                                         :hashed_password,:start_date,:end_date,:suspended,:created_at,:updated_at)
  end
end

app/controllers/staff/profile_controller.rb
class Staff::ProfileController < Staff::Base
  def index ;end
end

app/controllers/staff/sessions_controller.rb
class Staff::SessionsController < Staff::Base
  def new
    if current_staff_member
      redirect_to :staff_root
    else
      @form = Staff::LoginForm.new
      render :new
    end
  end
  def create
    @form = Staff::LoginForm.new(login_form_params)
    if @form.email.present?
      staff_member = StaffMember.find_by("LOWER(email)=?",@form.email.downcase)
    end
    if Staff::Authenticator.new(staff_member).authenticate(@form.password)
      if staff_member.suspended?
        flash.alert = "アカウントが停止されています"
        render :new
      else
        session[:staff_member_id] = staff_member.id
        flash.notice = "ログインしました"
        redirect_to :staff_root
      end
    else
      flash.alert = "メールアドレス、またはパスワードが正しくありません。"
      render :new
    end
  end
  def destroy
    session.delete(:staff_member_id)
    flash.alert = "ログアウトしました"
    redirect_to :staff_root
  end
  private def login_form_params
    params.require(:staff_login_form).permit(:email,:password)
  end
end

app/controllers/staff/top_controller.rb
class Staff::TopController < Staff::Base
  def index

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def document_title
    @title.present? ? "#{@title} -BAUKIS2021" : "BAUKIS2021"
  end
end

app/views/admin/profile/index.html.erb
<div class="table-wrapper">
  <div class="links">
    <%= link_to "新規登録",:new_admin_staff_member %>
  </div>
  <table class="listing">
    <tr>
      <th>氏名</th>
      <th>フリガナ</th>
      <th>メールアドレス</th>
      <th>入社日</th>
      <th>退職日</th>
      <th>停止フラグ</th>
      <th>アクション</th>
    </tr>
    <% @staff_members.each do |m| %>
      <tr>
        <td><%= m.family_name %> <%= m.given_name %></td>
        <td><%= m.family_name_kana %> <%= m.given_name_kana %></td>
        <td class="email"><%= m.email %></td>
        <td class="date"><%= m.start_date.strftime("%Y/%m/%d") %></td>
        <td class="date"><%= m.end_date.try(:strftime, "%Y/%m/%d") %></td>
        <td class="boolean">
          <%= m.suspended? ? raw("&#x2611;") : raw("&#x2610;") %>
        </td>
        <td class="actions">
          <%= link_to "編集", [ :edit, :admin, m ] %> |
          <%= link_to "削除", [ :admin, m ], method: :delete,
                      data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  </table>
</div>

app/views/admin/shared/_header.html.erb
<header>
  <%= link_to "BAUKIS2" ,:admin_root,class: "logo-mark" %>
  <%= content_tag(:span, flash.notice, class: "notice") if flash.notice %>
  <%= content_tag(:span, flash.alert, class: "notice")  if flash.alert%>
  <%=
    if current_administrator
      link_to "ログアウト", :admin_session,method: :delete
    else
      link_to "ログイン", :admin_login
    end
  %>
</header>

app/views/admin/staff_members/_form.html.erb
<div class="notes">
  <span class="mark">*</span>印のついた項目は必須項目です。
</div>
<div>
  <%= f.label :email,"メールアドレス",class: "required" %>
  <%= f.email_field :email, size: 32,required: true %>
</div>
<div>
  <%= f.label :password,"パスワード",class: "required" %>
  <%= f.password_field :password, size: 32,required: true %>
</div>

<div>
  <%= f.label :family_name,"氏名",class: "required" %>
  <%= f.text_field :family_name ,required: true %>
  <%= f.text_field :given_name ,required: true %>
</div>
<div>
  <%= f.label :family_name,"フリガナ",class: "required" %>
  <%= f.text_field :family_name_kana ,required: true %>
  <%= f.text_field :given_name_kana ,required: true %>
</div>
<div>
  <%= f.label :start_date,"入社日",class: "required" %>
  <%= f.date_field :start_date,required: true %>
</div>
<div>
  <%= f.label :end_date,"退職日",class: "required" %>
  <%= f.date_field :end_date %>
</div>
<div class="check-boxes">
  <%= f.check_box :suspended %>
  <%= f.label :suspended , "アカウント停止" %>
</div>

app/views/admin/staff_members/edit.html.erb
<% @title = "職員情報の編集" %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_with model: @staff_member, url: [ :admin, @staff_member ],local: true do |f| %>
    <%= render "form", f: f %>
    <div class="buttons">
      <%= f.submit "更新する" %>
      <%= link_to "キャンセル", :admin_staff_members %>
    </div>
  <% end %>
</div>

app/views/admin/staff_members/index.html.erb
<% @title = "職員管理" %>
<h1><%= @title %></h1>
<div class="table-wrapper">
  <div class="links">
    <%= link_to "新規登録", :new_admin_staff_member %>
  </div>
  <table class="listing">
    <tr>
      <th>氏名</th>
      <th>フリガナ</th>
      <th>メールアドレス</th>
      <th>入社日</th>
      <th>退職日</th>
      <th>停止フラグ</th>
      <th>アクション</th>
    </tr>
    <% @staff_members.each do |m| %>
      <tr>
        <td><%= m.family_name %> <%= m.given_name %></td>
        <td><%= m.family_name_kana %> <%= m.given_name_kana %></td>
        <td class="email"><%= m.email %></td>
        <td class="date"><%= m.start_date.strftime("%Y/%m/%d") %></td>
        <td class="date"><%= m.end_date.try(:strftime, "%Y/%m/%d") %></td>
        <td class="boolean">
          <%= m.suspended? ? raw("&#x2611;") : raw("&#x2610;") %>
        </td>
        <td class="actions">
          <%= link_to "編集", [ :edit, :admin, m ] %> |
          <%= link_to "削除", [ :admin, m ], method: :delete,
                      data: { confirm: "本当に削除しますか？" } %>
        </td>
      </tr>
    <% end %>
  </table>

  <div class="links">
    <%= link_to "新規登録", :new_admin_staff_member %>
  </div>
</div>

app/views/admin/staff_members/new.html.erb
<% @title = "職員の新規登録" %>
<h1><%= @title %></h1>

<div id="generic-form">
  <%= form_with model: @staff_member, url: [ :admin, @staff_member ],local: true do |f| %>
    <%= render "form", f: f %>
    <div class="buttons">
      <%= f.submit "登録" %>
      <%= link_to "キャンセル", :admin_staff_members %>
    </div>
  <% end %>
</div>

app/views/admin/top/dashboard.html.erb
<% @title = "ダッシュボード" %>

<h1><%= @title %></h1>
<ul class="menu">
  <li><%= link_to "職員管理",admin_staff_members_path %></li>
</ul>

app/views/admin/top/index.html.erb
<% @title = "管理者トップページ" %>
<h1><%= @title %></h1>

app/views/customer/shared/_header.html.erb
<header>
  <span class="logo-mark">BAUKIS0218</span>
</header>

app/views/customer/top/index.html.erb
<% @title = "ユーザートップページ" %>
<h1><%= @title %></h1>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= document_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "admin", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "admin/shared/header" %>
      <div id="container">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/customer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= document_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "customer", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
    <div id="wrapper">
      <%= render "customer/shared/header" %>
      <div id="container">
        <%= yield %>
      </div>
      <%= render "shared/footer" %>
    </div>
  </body>
</html>

app/views/layouts/staff.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= document_title %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "staff", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application", "data-turbolinks-track": "reload" %>
  </head>

  <body>
<!--    <div id="wrapper">-->
      <%#= render "staff/shared/header" %>
<!--      <div id="container">-->
        <%#= yield %>
<!--      </div>-->
      <%#= render "shared/footer" %>
<!--    </div>-->
    <%= yield %>
  </body>
</html>

app/views/shared/_footer.html.erb
<footer>
  <p>&copy;2021 エメトセレク</p>
</footer>

app/views/staff/profile/_flex.html.erb
<section id="d-flex">
  <div class="item">
    <div class="d-flex p-2">デフォルトのFlexコンテナ！</div>
    <div class="d-inline-flex p-2">インラインFlexコンテナ！</div>
  </div>
  <section class="item d-flex flex-row">
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
  </section>
  <div class="item d-flex flex-row-reverse">
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
  </div>
  <div class="item d-flex flex-column">
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
  </div>
  <section id="box">
    <div class="item d-flex flex-column">
      <div class="p-2">Flexアイテム1</div>
      <div class="p-2">Flexアイテム2</div>
      <div class="p-2">Flexアイテム3</div>
    </div>
  </section>
  <section id="box">
    <div class="d-flex align-items-start item">
      <div class="p-2">Flexアイテム1</div>
      <div class="p-2">Flexアイテム2</div>
      <div class="p-2">Flexアイテム3</div>
    </div>
  </section>
  <section id="box">
    <div class="d-flex align-items-stretch">
      <div class="p-2">Flexアイテム1</div>
      <div class="p-2">Flexアイテム2</div>
      <div class="p-2">Flexアイテム3</div>
    </div>
  </section>
  <div class="d-flex item">
    <div class="p-2 flex-fill">コンテンツが長めのFlexアイテム1</div>
    <div class="p-2 flex-fill">Flexアイテム2</div>
    <div class="p-2 flex-fill">Flexアイテム3</div>
  </div>
  <div class="d-flex flex-column item" style="height:200px;">
    <div class="p-2 flex-fill">コンテンツが長めの<br>Flexアイテム1</div>
    <div class="p-2 flex-fill">Flexアイテム2</div>
    <div class="p-2 flex-fill">Flexアイテム3</div>
  </div>
  <div class="d-flex item">
    <div class="mr-auto p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
  </div>
  <div class="d-flex item">
    <div class=" p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="ml-auto p-2">Flexアイテム3</div>
  </div>
  <div class="d-flex item">
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
  </div>
  <div class="d-flex flex-wrap item">
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
    <div class="p-2">Flexアイテム1</div>
    <div class="p-2">Flexアイテム2</div>
    <div class="p-2">Flexアイテム3</div>
  </div>
</section>

app/views/staff/profile/_nav.html.erb
<ul class="nav">
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<ul class="nav justify-content-center">
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<ul class="nav nav-tabs">
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<ul class="nav nav-tabs flex-column">
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<ul class="nav nav-fill">
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<ul class="nav ">
  <li class="nav-item dropdown">
    <a href="" class="nav-link dropdown-toggle" data-toggle="dropdown"  role="button" aria-haspopup="true" aria-expanded="false">ドロップダウン</a>
    <div class="dropdown-menu">
      <%= link_to :staff_root do %>
        <a href="" class="dropdown-item">staff</a>
      <% end %>
      <%= link_to :staff_root do %>
        <a href="" class="dropdown-item">staff</a>
      <% end %>
      <%= link_to :staff_root do %>
        <a href="" class="dropdown-item">staff</a>
      <% end %>
      <%= link_to :staff_root do %>
        <a href="" class="dropdown-item">staff</a>
      <% end %>
    </div>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<ul class="nav nav-tabs">
  ...
  <li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">ドロップダウン</a>
    <div class="dropdown-menu">
      <a class="dropdown-item" href="#">メニュー1</a>
      ...
    </div>
  </li>
  ...
</ul>
<ul class="nav nav-tabs" role="tablist">
  <li class="nav-item" role="presentation">
    <%= link_to :staff_root do %>
      <a href="#home"  id="home-tab"class="nav-link" data-toggle="tab" aria-controls="home" aria-selected="true">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
  <li class="nav-item">
    <%= link_to :staff_root do %>
      <a href="" class="nav-link">foo</a>
    <% end %>
  </li>
</ul>
<div id="myTabContent" class="tab-content mt-3">
  <div id="home" class="tab-pane " role="tabpanel" aria-labelledby="home-tab">
    foobarfoobar
  </div>
</div>

app/views/staff/profile/_profile.html.erb
<section id="profile-page">
  <div class="wrapper">
    <section class="section-profile-cover section-shaped my-o">
      <%= image_tag "mohamed.jpg" %>
    </section>
    <section class="section-profile">
      <div class="container">
        <div class="card shadow mt--450">
          <div class="px-4">
            <div class="row justify-content-center">
              <div class="col-lg-3 order-lg-2">
                <div class="card-profile-image">
                  <%= image_tag "mohamed.jpg",class: "rounded-circle" %>
                </div>
              </div>
              <div class="col-lg-4 order-lg-3 text-lg-right align-self-lg-center">
                <div class="item py-4 mt-lg-0">
                  <a href="" class="btn btn-info btn-fs mr-4">Connect</a>
                  <a href="" class="btn btn-default btn-fs float-right">Message</a>
                </div>
              </div>
              <div class="col-lg-4 order-lg-1">
                <div class="card-profile-stats d-flex justify-content-center">
                  <div>
                    <span class="heading">22</span>
                    <span class="description">Friends</span>
                  </div>
                  <div>
                    <span class="heading">10</span>
                    <span class="description">Photos</span>
                  </div>
                  <div>
                    <span class="heading">89</span>
                    <span class="description">Comments</span>
                  </div>
                </div>
              </div>
            </div>
            <div class="text-center mt-5">
              <h3>Jessica Jones<span class="font-weight-light">, 27</span></h3>
              <div class="h6 font-weight-300">Bucharest, Romania</div>
              <div class="h6 mt-4">Solution Manager - Creative Tim Officer</div>
              <div>University of Computer Science</div>
            </div>
            <div class="mt-5 py-5 border-top text-center">
              <div class="row justify-content-center">
                <div class="col-lg-9">
                  <p>An artist of considerable range, Ryan — the name taken by Melbourne-raised, Brooklyn-based Nick Murphy — writes, performs and records all of his own music, giving it a warm, intimate feel with a solid groove structure. An artist of considerable range.</p>
                  <a href="javascript:;">Show more</a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </div>
</section>

app/views/staff/shared/_header.html.erb
<header>
  <span class="logo-mark">BAUKIS0218</span>
  <%= content_tag(:span, flash.notice, class: "notice") if flash.notice %>
  <%= content_tag(:span, flash.alert, class: "notice")  if flash.alert%>
  <%=
    if current_staff_member
      link_to "ログアウト", :staff_session,method: :delete
    else
      link_to "ログイン", :staff_login
    end
  %>
</header>